/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author marcos
 */
public class IniciarCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public IniciarCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldCodigoDeBarra = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtValorUnitario = new javax.swing.JTextField();
        txtQuantidadeDoProduto = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesoUnitario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPesoTotal = new javax.swing.JTextField();
        txtValorUnitario1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnConfirmaItem = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtQuantidadeDeItens = new javax.swing.JTextField();
        txtCodigoDeBarra = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JToggleButton();
        btnCancelaItem = new javax.swing.JToggleButton();

        jTextField5.setText("jTextField5");

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 622, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldCodigoDeBarra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCodigoDeBarra.setText("77788473");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldCodigoDeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldCodigoDeBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValorUnitario.setText("R$ 8,56");
        txtValorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnitarioActionPerformed(evt);
            }
        });

        txtQuantidadeDoProduto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtQuantidadeDoProduto.setText("1");
        txtQuantidadeDoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeDoProdutoActionPerformed(evt);
            }
        });

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSubtotal.setText("R$ 8,56");

        txtValorTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtValorTotal.setText("R$12,89");
        txtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTotalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("VALOR UNITÁRIO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("QUANTIDADE");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("VALOR TOTAL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SUB_TOTAL ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PESO UNITÁRIO");

        txtPesoUnitario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPesoUnitario.setText("400gr");
        txtPesoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoUnitarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PESO TOTAL COMPRA");

        txtPesoTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPesoTotal.setText("900gr");
        txtPesoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoTotalActionPerformed(evt);
            }
        });

        txtValorUnitario1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValorUnitario1.setText("BOLACHA");
        txtValorUnitario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnitario1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("NOME DO PRODUTO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoUnitario)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPesoTotal))
                    .addComponent(txtValorUnitario1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(txtValorUnitario, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPesoTotal, txtPesoUnitario});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorUnitario1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesoUnitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtPesoTotal, txtSubtotal, txtValorUnitario});

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 560, 440));

        btnConfirmaItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmaItem.setForeground(new java.awt.Color(0, 255, 0));
        btnConfirmaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cart_add.png"))); // NOI18N
        btnConfirmaItem.setText("CONFIRMAR ITEM");
        btnConfirmaItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaItemActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmaItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 220, 60));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 616, -1, 0));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("QUANTIDADE DE ITNES");

        txtQuantidadeDeItens.setBackground(new java.awt.Color(153, 255, 51));
        txtQuantidadeDeItens.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtQuantidadeDeItens.setText("3");
        txtQuantidadeDeItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeDeItensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtQuantidadeDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtQuantidadeDeItens))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 330, 50));

        txtCodigoDeBarra.setText("CODIGO_PRODUTO");
        getContentPane().add(txtCodigoDeBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comprasFuturo.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 460, 370));

        btnFinalizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bag_green.png"))); // NOI18N
        btnFinalizarCompra.setText("FINALIZAR COMPRAS");
        btnFinalizarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 180, 60));

        btnCancelaItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelaItem.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cart_remove.png"))); // NOI18N
        btnCancelaItem.setText("CANCELAR ITEM");
        btnCancelaItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaItemActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelaItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 220, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitarioActionPerformed

    private void txtQuantidadeDoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeDoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeDoProdutoActionPerformed

    private void txtPesoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoTotalActionPerformed

    private void txtQuantidadeDeItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeDeItensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeDeItensActionPerformed

    private void btnCancelaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaItemActionPerformed

JOptionPane.showConfirmDialog(null, "DESEJA REALMENTE CANCELAR ITEM");
    }//GEN-LAST:event_btnCancelaItemActionPerformed

    private void btnConfirmaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmaItemActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        
       
        JDesktopPane desktop = new JDesktopPane();
        setContentPane(desktop);
        JFCartão frame = new JFCartão();
        frame.setVisible(true);
        desktop.add(frame);
      
        try {
            frame.setSelected(true);
            setContentPane(desktop);
        
        } catch (java.beans.PropertyVetoException e) {}
       
         
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void txtPesoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoUnitarioActionPerformed

    private void txtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalActionPerformed

    private void txtValorUnitario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitario1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelaItem;
    private javax.swing.JToggleButton btnConfirmaItem;
    private javax.swing.JToggleButton btnFinalizarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldCodigoDeBarra;
    private javax.swing.JLabel txtCodigoDeBarra;
    private javax.swing.JTextField txtPesoTotal;
    private javax.swing.JTextField txtPesoUnitario;
    private javax.swing.JTextField txtQuantidadeDeItens;
    private javax.swing.JTextField txtQuantidadeDoProduto;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValorUnitario;
    private javax.swing.JTextField txtValorUnitario1;
    // End of variables declaration//GEN-END:variables
}
