/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author marcos
 */
public class JFMenu_principal extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu_principal
     */
    public JFMenu_principal() {
        //this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        tela_interna = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        MenuIniciarCompra = new javax.swing.JMenuItem();
        OfertasRelampago = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuPaguamento = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        MenuCadastrarCliente = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA SUPERMERCADO ");
        setPreferredSize(new java.awt.Dimension(1000, 700));

        tela_interna.setPreferredSize(new java.awt.Dimension(900, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Carrinho Super Nosso 3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tela_interna.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tela_interna.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tela_internaLayout = new javax.swing.GroupLayout(tela_interna);
        tela_interna.setLayout(tela_internaLayout);
        tela_internaLayout.setHorizontalGroup(
            tela_internaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela_internaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(746, 746, 746))
        );
        tela_internaLayout.setVerticalGroup(
            tela_internaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela_internaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cart_add.png"))); // NOI18N
        MenuInicio.setText("INICIAR COMPRA");
        MenuInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInicioActionPerformed(evt);
            }
        });

        MenuIniciarCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        MenuIniciarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cart.png"))); // NOI18N
        MenuIniciarCompra.setText("Iniciar Compras");
        MenuIniciarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuIniciarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIniciarCompraActionPerformed(evt);
            }
        });
        MenuInicio.add(MenuIniciarCompra);

        jMenuBar2.add(MenuInicio);

        OfertasRelampago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/offer_50.png"))); // NOI18N
        OfertasRelampago.setText("OFERTAS RELAMPAGO");
        OfertasRelampago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OfertasRelampago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfertasRelampagoActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hot.png"))); // NOI18N
        jMenuItem3.setText("PRODUTOS");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        OfertasRelampago.add(jMenuItem3);

        jMenuBar2.add(OfertasRelampago);

        MenuPaguamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dollar.png"))); // NOI18N
        MenuPaguamento.setText("PAGAMENTO ");
        MenuPaguamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/mastercard.png"))); // NOI18N
        jMenuItem1.setText("Cartões ");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuPaguamento.add(jMenuItem1);

        jMenuBar2.add(MenuPaguamento);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bag_green.png"))); // NOI18N
        jMenu1.setText("CADASTRO PRODUTO");

        jMenuItem2.setText("Cadastrar Produto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar2.add(jMenu1);

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/mail.png"))); // NOI18N
        menuCadastro.setText("CADASTRO CLIENTE");
        menuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuCadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customer_service.png"))); // NOI18N
        MenuCadastrarCliente.setText("Cadastrar Cliente");
        MenuCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(MenuCadastrarCliente);

        jMenuBar2.add(menuCadastro);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela_interna, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tela_interna, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuIniciarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIniciarCompraActionPerformed
       IniciarCompra tela = new IniciarCompra();
       
       tela_interna.add(tela);
       tela.setVisible(true);
    
    }//GEN-LAST:event_MenuIniciarCompraActionPerformed

    private void MenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInicioActionPerformed
      
    }//GEN-LAST:event_MenuInicioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFCartão pague = new JFCartão();
        
       tela_interna.add(pague);
       pague.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarClienteActionPerformed
        JFcadastroUsuario cadatroUser = new JFcadastroUsuario();
       
       tela_interna.add(cadatroUser);
      cadatroUser.setVisible(true);
      
    }//GEN-LAST:event_MenuCadastrarClienteActionPerformed

    private void OfertasRelampagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfertasRelampagoActionPerformed
       /*JFofertaRelanpago tela = new JFofertaRelanpago();
       
       tela_interna.add(tela);
       tela.setVisible(true);*/
    }//GEN-LAST:event_OfertasRelampagoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
JFofertaR ofer = new JFofertaR();
       tela_interna.add(ofer);
       ofer.setVisible(true);    
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    CadastroProduto tela = new CadastroProduto();
     
       tela_interna.add(tela);
       tela.setVisible(true); 
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCadastrarCliente;
    private javax.swing.JMenuItem MenuIniciarCompra;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JMenu MenuPaguamento;
    private javax.swing.JMenu OfertasRelampago;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JDesktopPane tela_interna;
    // End of variables declaration//GEN-END:variables
}
